Bug/compound topography
ContactEngineering/SurfaceTopography pull request #281
Opened 2023-01-17 12:47 UTC by sannant

2023-01-17 14:13 UTC, sannant commented
@pastewka , once this branch is merged we should do a release, since it is currently blocking ContactMechanics and the tip artefacts are a major issue

2023-01-18 07:41 UTC, pastewka requested changes

2023-01-18 07:41 UTC, pastewka commented on SurfaceTopography/ChangeLog.md
>  v1.3.1 (not yet released)
1.3.1 was released Jan 14

2023-01-18 07:55 UTC, sannant commented on SurfaceTopography/ChangeLog.md
>  v1.3.1 (not yet released)
Ah sorry I forgot to pull

2023-01-18 08:57 UTC, pastewka approved these changes
Should I do a new release?

2023-01-18 09:26 UTC, merged