Bug/translated topography
ContactEngineering/SurfaceTopography pull request #346
Opened 2023-12-15 09:45 UTC by sannant

2023-12-15 10:40 UTC, pastewka approved these changes

2023-12-15 11:02 UTC, sannant commented
```
def test_translate_setter():
    topography = Topography(np.array([[0, 1, 0], [0, 0, 0]]),
                            physical_sizes=(4., 3.))

    translated_t = topography.translate()

    translated_t.offset = (1, 0)
    assert (translated_t.heights()
            ==
            np.array([[0, 0, 0],
                      [0, 1, 0]])).all()
    topography = Topography(np.array([[0, 1, 0], [0, 0, 0]]),
                            physical_sizes=(4., 3.), periodic=True)
    assert topography.translate(offset=(1, 0)).is_periodic

```
this previously existing test  implies that it is ok to translate nonperiodic topographies (the first part, since by default, topographies are nonperiodic).

I think that this is bad behavior because the translation is implemented via a numpy.roll.

Do we agree to raise an error when a nonperiodic topography is translated ?

2024-01-13 17:04 UTC, sannant commented
@pastewka I need your opinion on the comment above

2024-01-13 17:06 UTC, pastewka commented
Agree to raise the error. Can you indicate in the changelog that this is an API change (prefix with API, not changelog) which triggers a new major version release.

2024-01-13 17:07 UTC, sannant commented
Ok

2024-01-13 17:43 UTC, pastewka requested changes

2024-01-13 17:43 UTC, pastewka commented on SurfaceTopography/ChangeLog.md
> +v1.12.3 (13Jan24)
Can you bump version to v1.13.0 because this is a breaking change?

2024-01-13 18:33 UTC, pastewka approved these changes

2024-01-13 18:33 UTC, merged